[package]
name = "rust-gear-book-playground"
version = "0.1.0"
authors = ["ynishimura <ynishimura0922@gmail.com>"]
edition = "2018"

[features]

[dependencies]
fstrings = "0.2.3"
futures = "0.3.17"
tokio = { version = "0.2.21", features = ["macros"]}
rand = "0.7.3"